name: CI-Main

on:
  push:
    branches:
      - "main"

jobs:
  test-main:
    uses: ./.github/workflows/python-tag-release.yaml
    with:
      python_version: 3.8
      source_directory: python_codeartifact_demo
      create_tag: true
      aws_region: "eu-central-1"
    secrets: inherit
