name: CI-Main

on:
  push:
    branches:
      - "main"

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
      - name: Set Default Branch Name
        run: "git config --global init.defaultBranch main"
      
      - name: Set Default User Email
        run: git config --global user.email "dipanjan.kailthya@gmail.com"

      - name: Set Default User Name
        run: git config --global user.name "Dipanjan Kailthya"

      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
         token: ${{ secrets.AUTOTAG_TOKEN }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Update Packages
        run: "sudo apt-get update -y && sudo apt-get upgrade -y"
      
      - name: Install Poetry
        run: "pip install -r requirements-cicd.txt"
      
      - name: Install Dependencies
        run: make install

      - name: Run Code Quality checks
        run: make lint

      - name: Test with pytest
        run: make test

      - name: Build Package
        run: make build
     
      - name: Create Tag
        run: "auto-tag -b main -r . -u origin --skip-tag-if-one-already-present --append-v-to-tag" 
