name: CI-Main

on:
  push:
    branches:
      - "main"

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Update Packages
        run: "sudo apt-get update -y && sudo apt-get upgrade -y"
      
      - name: Print Git Version
        run: "git --version"
      
      - name: Check rev-parse command"
        run: "git rev parse main --"
 
      - name: Install Poetry
        run: "pip install -r requirements-cicd.txt"
      
      - name: Install Dependencies
        run: make install

      - name: Run Code Quality checks
        run: make lint

      - name: Test with pytest
        run: make test

      - name: Build Package
        run: make build
     
      - name: Create Auto Tag
        run: "auto-tag -b main -r . -u origin --skip-tag-if-one-already-present --append-v-to-tag" 
