name: CI

on:
  workflow_run:
    workflows:
      - poetry-build-test-release
    types: [ completed ]

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry

      - name: Install dependencies
        run: poetry install

#      - name: Authenticate to CodeArtifact
#        uses: source-ag/codeartifact-login-action@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: eu-central-1
#          role-to-assume: ${{ secrets.PACKAGE_REPOSITORY_ROLE }}
#          codeartifact-domain: my-domain
#          codeartifact-domain-owner: 123456789012
#          codeartifact-repository: my-python-packages
#          configure-poetry: true
#
#      - name: Publish to CodeArtifact
#        run: poetry publish
