name: publish-codeartifact

on:
  workflow_run:
    workflows:
      - poetry-build-test-release
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry

      - name: Install dependencies
        run: poetry install
      - name: Install Poetry Dynamic Versioning Plugin
        run: poetry self add poetry-dynamic-versioning[plugin]
      - name: Install Python Semantic Release
        run: pip install python-semantic-release==7.33.2
      - name: Checkout Release Tag
        run: |
          RELEASE_VERSION="v$(semantic-release print-version --current)"
          git switch --detach ${RELEASE_VERSION}
      - name: Run Poetry Build
        run: poetry build
      - name: Authenticate to CodeArtifact
        uses: source-ag/codeartifact-login-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          codeartifact-domain: ca-demo
          codeartifact-domain-owner: 381665779871
          codeartifact-repository: ca-repo
          configure-poetry: true

      - name: Publish to CodeArtifact
        run: poetry publish
