name: poetry-build-test-release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python_version: ['3.8', '3.9', '3.10']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Export Poetry Lockfile
        run: poetry export --with dev --without-hashes --without-urls -o requirements-dev.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Install requirements
        run: pip install -r requirements-dev.txt

      - name: Test with pytest
        run: poetry run pytest

      - name: Build Package
        run: poetry build

  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - test
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python Semantic Release
        run: pip install python-semantic-release==7.33.2
      - name: Create Release
        id: create-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish --verbosity=DEBUG
