name: CI-Tag-Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: ./.github/workflows/python-tag-release.yaml
    with:
      python_version: 3.8
      source_directory: python_codeartifact_demo
      deploy: true
      ca_domain_owner: "381665779871"
      ca_domain: "ca-demo"
      ca_repository: "ca-repo"
      ca_role: "arn:aws:iam::381665779871:role/CodeArtifactAccessRole"
      aws_region: "eu-central-1"
    secrets: inherit
