name: CI-Tag-Release

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  code-quality-check:
    if: startsWith(github.ref, 'refs/heads/')
    uses: ./.github/workflows/poetry-build-test-quality-check.yaml
    with:
      python_version: 3.8
      source_directory: python_codeartifact_demo

