name: poetry-build-test-code-quality

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  poetry-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set Default Branch Name
        run: "git config --global init.defaultBranch main"

      - name: Set Default User Email
        run: git config --global user.email "dipanjan.kailthya@gmail.com"

      - name: Set Default User Name
        run: git config --global user.name "Dipanjan Kailthya"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true

      - name: Test with pytest
        run: poetry run pytest -v --cov ${{ inputs.source_directory }}

      - name: Build Package
        run: poetry build
