name: CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
    release:
      types:
        - published

jobs:
  code-quality-check:
    if: startsWith(github.ref, 'refs/heads/')
    uses: ./.github/workflows/poetry-build-test-quality-check.yaml
    with:
      python_version: 3.8
      source_directory: python_codeartifact_demo

  create-release:
    needs:
      - code-quality-check
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  deploy-release:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/poetry-release.yaml
    with:
      ca_domain_owner: "381665779871"
      ca_domain: "ca-demo"
      ca_repository: "ca-repo"
      ca_role: "arn:aws:iam::381665779871:role/CodeArtifactAccessRole"
      aws_region: "eu-central-1"
    secrets: inherit
