name: poetry-release

on:
  workflow_dispatch:
    inputs:
      python_version:
        required: false
        type: string
        default: 3.8
      source_directory:
        required: true
        type: string
      release_version:
        required: true
        type: string
        default: false
      ca_domain_owner:
        required: true
        type: string
      ca_domain:
        required: true
        type: string
      ca_repository:
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: "eu-central-1"
      ca_role:
        required: true
        type: string
      ca_session_duration:
        required: false
        type: string
        default: "900"

    secrets:
        AWS_ACCESS_KEY_ID:
          required: false
        AWS_SECRET_ACCESS_KEY:
          required: false

jobs:
  poetry-release-package:
    runs-on: ubuntu-latest
    steps:
      - name: Set Default Branch Name
        run: "git config --global init.defaultBranch main"

      - name: Set Default User Email
        run: git config --global user.email "dipanjan.kailthya@gmail.com"

      - name: Set Default User Name
        run: git config --global user.name "Dipanjan Kailthya"

      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: Switch to Tag
        run: git switch -c ${{ inputs.release_version }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python_version }}

      - name: Update Packages
        run: "sudo apt-get update -y && sudo apt-get upgrade -y"

      - name: Install CI Requirements
        run: |
          cat > /tmp/requirements-ci.txt << EOF 
          poetry
          poetry-dynamic-versioning
          twine
          awscli
          EOF
          pip install -r /tmp/requirements-ci.txt      

      - name: Install Project Dependencies
        run: poetry install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ inputs.ca_role }}
          role-duration-seconds: ${{ inputs.ca_session_duration }}

      - name: Publish Package to CodeArtifact (if tag)
        run: |
          poetry build
          aws codeartifact login \
            --tool twine \
            --domain-owner ${{ inputs.ca_domain_owner }} \
            --domain ${{ inputs.ca_domain }} \
            --repository ${{ inputs.ca_repository }}        
          twine upload --repository codeartifact dist/*
        if: startsWith(github.ref, 'refs/tags/v')
